name: Development CI
on:
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-versions: [19.3.0, 18.0.0]

    steps:
      - uses: actions/checkout@v3
      - name: use node.js version ${{ matrix.node-version }}
      - uses: actions/setup-node@v3
        with:
          node-versions: ${{ matrix.node-version }}
      - run: npm run lint



