version: "3.9"

services:
  web:
    build:
      context: .
    container_name: dev_web
    env_file: .env
    depends_on:
      - db
    ports:
      - 3000:8000
    volumes:
      - .:/usr/src/app
    networks:
      - airshow

  db:
    image: postgres:12.13-alpine3.17
    container_name: dev_db
    restart: always
    env_file: .env
    volumes:
      - ./.seed/:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - airshow

volumes:
  db:

networks:
  airshow:
