version: "3.9"

services:
  web:
    build:
      context: .
    env_file: .env
    depends_on:
      - db
    networks:
      - aircraft

  db:
    image: postgres:12.13-alpine3.17
    restart: always
    env_file: .env
    volumes:
      - .seed/:/docker-entrypoint-initdb.d
      - db:/var/lib/postgresql/data
    networks:
      - aircraft

volumes:
  db:

networks:
  aircraft:
